### ISSUE TITLE
Failing to compile due to argument mismatch

### ISSUE THREAD

**Issue by jreesun** [diybitcoinhardware/secp256k1-embedded#1]
Pulled down the latest version of `embit` and `secp256k1-embedded` and ran into this problem when compiling:
```
libsecp256k1.c:721:15: error: too few arguments to function 'secp256k1_schnorrsig_verify'
     int res = secp256k1_schnorrsig_verify(ctx, sig, msg, &pub);

libsecp256k1.c:793:15: error: too many arguments to function 'secp256k1_schnorrsig_sign'
         res = secp256k1_schnorrsig_sign(ctx, sig, msgbuf.buf, (secp256k1_keypair *)keypair, NULL, NULL);

libsecp256k1.c:804:15: error: too many arguments to function 'secp256k1_schnorrsig_sign'
         res = secp256k1_schnorrsig_sign(ctx, sig, msgbuf.buf, (secp256k1_keypair *)keypair, NULL, data);
```

Is there something missing on my end that could be causing this?

**Comment by stepansnigirev** [comment]
Just noticed it yesterday as well... Looks like schnorrsig bindings in `libsecp256k1` and `libsecp256k1-zkp` are slightly different.
I'll fix it ASAP.

**Comment by stepansnigirev** [comment]
I think these two commits fixed it:
https://github.com/diybitcoinhardware/secp256k1-embedded/commit/1102dababed4e97e46fd633884039f6916807420 - fix schnorrsig_sign
https://github.com/diybitcoinhardware/secp256k1-embedded/commit/10ab83293949d80fb3a2ca1bf32a1b5c60a42920 - fix schnorrsig_verify

**Comment by jreesun** [comment]
Thanks for addressing this so quickly!

That resolves the compilation issues 🎉
