### ISSUE TITLE
mpy API regression?

### ISSUE THREAD

**Issue by jreesun** [diybitcoinhardware/secp256k1-embedded#2]
After successfully building the module due to your fixes in #1, I ran into another issue that took some digging to figure out.

In the latest version of `embit`, there are a few calls to `secp256k1.ec_privkey_add` and `secp256k1.ec_pubkey_add` that can't be resolved anymore. It appears that these functions disappeared at some point in the past few months:
https://github.com/diybitcoinhardware/secp256k1-embedded/blob/690b81679e5046c8046127bd11130f12ffe095d3/mpy/libsecp256k1.c#L532
https://github.com/diybitcoinhardware/secp256k1-embedded/blob/690b81679e5046c8046127bd11130f12ffe095d3/mpy/libsecp256k1.c#L593

I added those functions back and was able to get everything working. Here's a PR to add those back:
https://github.com/diybitcoinhardware/secp256k1-embedded/pull/3

**Comment by stepansnigirev** [comment]
Thank you! I was mostly working and testing `zkp` branch over the last few months, looks like I broke a few things in the main branch...
